defaults:
  - sampling: random

_target_: panza.llm.OllamaLLM
name: "custom"
gguf_file: "/nfs/scistore19/alistgrp/ajovanov/PanzaMail/custom.gguf"
remove_prompt_from_stream: false
overwrite_model: false