defaults:
  - base
  - user: default
  - finetuning: full
  - writer/prompting/email_prompting@preprocessing.prompting


model: "ISTA-DASLab/Meta-Llama-3-8B-Instruct"
num_epochs: 1
lr: 1e-4
batch_size: 8
model_precision: bf16 # bf16 or fp32

preprocessing:
  model: ${model}
  prompting:
    number_rag_emails: 0
    number_thread_emails: 0