defaults:
  - base
  - writer: summary
  - writer/prompting/retriever/faiss@retriever

batch_size: 8
data_path: ${user.data_dir}/${user.username}_clean.jsonl
checkpoint: "microsoft/Phi-3-mini-4k-instruct"
force: false
rag_embedding_chunk_size: 3000
rag_embedding_chunk_overlap: 3000
rag_embedding_model: "sentence-transformers/all-mpnet-base-v2"