email_address: "abc@xyz.com"  # Change this to your email address!
username: "abc"  # This identifies the user in the users directory and the names of the emails files.

data_dir: ${panza_workspace}/data

system_preamble_path: ${panza_workspace}/prompt_preambles/system_preamble.txt
user_preamble_path: ${panza_workspace}/prompt_preambles/user_preamble.txt
rag_preamble_path: ${panza_workspace}/prompt_preambles/rag_preamble.txt
thread_preamble_path: ${panza_workspace}/prompt_preambles/thread_preamble.txt
